// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	getKeychainToken: () => typedError<string, string>(__TAURI_INVOKE("get_keychain_token")),
	setKeychainToken: (token: string) => typedError<null, string>(__TAURI_INVOKE("set_keychain_token", { token })),
	deleteKeychainToken: () => typedError<null, string>(__TAURI_INVOKE("delete_keychain_token")),
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

