export {
  ApiError,
  replayOfflineQueue,
  getHealth,
  register,
  createToken,
  loginWithProvider,
  getCallbackUrl,
  getMe,
  deleteAccount,
  getProviders,
  getMessages,
  getMessage,
  markAsRead,
  archiveMessage,
  snoozeMessage,
  trashMessage,
  sendMessage,
  toggleStar,
  updateLabels,
  bulkAction,
  searchMessages,
  searchEvents,
  getAttachmentRedirectUrl,
  createSyncStream,
  triggerSync,
  getCalendars,
  getEvents,
  createEvent,
  updateEvent,
  deleteEvent,
} from './client.js';

export * from './client.js';
export { queryClient } from './query.js';

export type {
  HealthResponse,
  RegisterResponse,
  TokenResponse,
  ProviderBranding,
  PaginatedMessages,
  Message,
  FullMessage,
  Attachment,
  SearchResult,
  Calendar,
  CalendarEvent,
  EventSearchResult,
  Snippet,
  Signature,
} from './client.js';
export { getSettings, updateSettings } from './client.js';
